name = "Humbert"
uuid = "f898d6e2-9e9b-447d-aaae-af982ff5659f"
authors = ["Eda Kirimli <eda.kirimli@bristol.ac.uk>", "Gaurish Korpal <gkorpal@arizona.edu>"]
version = "0.1.0"

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
JuliaFormatter = "2.1.2"
Oscar = "1.2.2"
